version: '3'
services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5055:5055"
    restart: always
    volumes:
      - .:/sql_alchemy
    env_file:
      - .env
    depends_on:
      - mysql_db
    container_name: flask_app
    
  mysql_db:
    image: mysql:5.7
    env_file:
        - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./.data/db:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: always
    container_name: mysql_db